export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CREATE_TRIP_START = 'CREATE_TRIP_START';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_FAIL = 'CREATE_TRIP_FAIL';
export const CREATE_INIT = 'CREATE_INIT';
export const SHOW_FULL_TRIP = 'SHOW_FULL_TRIP';

export const UPDATE_TRIP_START = 'UPDATE_TRIP_START';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
export const UPDATE_TRIP_FAIL = 'UPDATE_TRIP_FAIL';
export const TRIP_FINISH_UPDATE = 'TRIP_FINISH_UPDATE';
export const TRIP_CREATED = 'TRIP_CREATED';
export const CHANGE_TRIP_STATUS = 'CHANGE_TRIP_STATUS';


export const CREATE_CAR_START = 'CREATE_CAR_START';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const CREATE_CAR_FAIL = 'CREATE_CAR_FAIL';
export const CREATE_CAR_FINISH = 'CREATE_CAR_FINISH';

export const FETCH_TRIPS_START = 'FETCH_TRIPS_START';
export const FETCH_TRIP_START = 'FETCH_TRIP_START';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';
export const FETCH_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const DISMOUNT_SEARCH = 'DISMOUNT_SEARCH';
export const DISMOUNT_TRIP = 'DISMOUNT_TRIP';
export const DISMOUNT_ADMIN = 'DISMOUNT_ADMIN';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const SHOW_FULL_USER = 'SHOW_FULL_USER';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const USER_FINISH_UPDATE = 'USER_FINISH_UPDATE';
export const USER_CREATED = 'USER_CREATED';



