export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CREATE_TRIP_START = 'CREATE_TRIP_START';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_FAIL = 'CREATE_TRIP_FAIL';
export const CREATE_INIT = 'CREATE_INIT';
export const SHOW_FULL_TRIP = 'SHOW_FULL_TRIP';

export const FETCH_TRIPS_START = 'FETCH_TRIPS_START';
export const FETCH_TRIP_START = 'FETCH_TRIP_START';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';
export const FETCH_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const FETCH_USER_IMAGE_START = 'FETCH_USER_IMAGE_START';
export const FETCH_CAR_IMAGE_START = 'FETCH_CAR_IMAGE_START';
export const FETCH_USER_IMAGE_SUCCESS = 'FETCH_USER_IMAGE_SUCCESS';
export const FETCH_CAR_IMAGE_SUCCESS = 'FETCH_CAR_IMAGE_SUCCESS';
export const FETCH_USER_IMAGE_FAIL = 'FETCH_USER_IMAGE_FAIL';
export const FETCH_CAR_IMAGE_FAIL = 'FETCH_CAR_IMAGE_FAIL';